name: movie_app_final
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  sqflite_common_ffi: ^2.3.0+4
  image_picker: ^1.0.4
  http: ^1.1.0
  flutter_dotenv: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/generic.jpg
    - .env